
const token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTY1NTc2MjYsImV4cCI6MTc1NjU2MTIyNn0.md8_yHDXPNYnI7hTqbQEVRnvRj4BFHoLO0xF9dNiszI"

### GET ALL USERS
GET http://localhost:3000/users
### GET LoggedLL USERS
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiX2RhdmlzYW5jaGV6IiwiaWF0IjoxNzU3NTc4MDc2LCJleHAiOjE3NTc1ODE2NzZ9.2VItkLDy9-6TX2eHh9SnlmEu9yXxKk17Tq9Xt6MPQJM

###update user bio
PUT http://localhost:3000/description
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2FybGEzIiwiaWF0IjoxNzU3MTQ0NDc3LCJleHAiOjE3NTcxNDgwNzd9.bWSMJF9W8Q2c2ezaMINv-mLe7Q5PHwhLgz1z04w4Gis

{
    "description":"xxxx"
}
###get user by username
GET http://localhost:3000/user/search?username=victorious

### GET ALL GROUPS
GET http://localhost:3000/groups
### GET GROUPS FROM USER
GET http://localhost:3000/groups/search?username=carla
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2FybGEiLCJpYXQiOjE3NTcxNjkyODUsImV4cCI6MTc1NzE3Mjg4NX0.9k-kV8qTC136X3Ri911_xay7VzDVTIwbOJHNQO6rhZI

### GET ALL USERGROUPS
GET http://localhost:3000/usergroups/search?group=
### GET ALL HEADERS
GET http://localhost:3000/headers
### GET ALL sections
GET http://localhost:3000/sections
### GET NEWS FROM SECTION OR HEADER
GET http://localhost:3000/news/search?
### GET  most liked NEWS
GET http://localhost:3000/news/most-liked


### GET ALL LIKES FROM A NEW
GET http://localhost:3000/likes/search?id=aaaaaaaa-aaaa-aaaa-aaaa-aaaa20000005

### GET ALL Comments FROM A NEW
GET http://localhost:3000/comments/search?id=aaaaaaaa-aaaa-aaaa-aaaa-aaaa20000002
### GET ALL TAGS
GET http://localhost:3000/tags

###GET REQUESTS FROM THE GROUP I'M ADMIN OF
GET http://localhost:3000/my-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2FybGEiLCJpYXQiOjE3NTcxNDQ2MDEsImV4cCI6MTc1NzE0ODIwMX0.oBib3m-vgnpC45TC2JVPu33crEwrc43PGAgcQJmRa1c
###GET requests SENT BY ME
GET http://localhost:3000/pending-requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2FybGEiLCJpYXQiOjE3NTcxNDQ2MDEsImV4cCI6MTc1NzE0ODIwMX0.oBib3m-vgnpC45TC2JVPu33crEwrc43PGAgcQJmRa1c

###DELETE REQUEST BY request id
DELETE http://localhost:3000/request
Content-Type: application/json; charset=utf-8
Authorization: Bearer 

{
    "id":"ssss"
}

###DELETE comment BY commment id
DELETE http://localhost:3000/comment
Content-Type: application/json; charset=utf-8
Authorization: Bearer 

{
    "id":"ssss"
}
###DELETE like BY like id
DELETE http://localhost:3000/like
Content-Type: application/json; charset=utf-8
Authorization: Bearer 

{
    "id":"ssss"
}

### MAKE REQUEST TO JOIN GROUP
POST http://localhost:3000/make-request
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2FybGEiLCJpYXQiOjE3NTcxNjI0MjcsImV4cCI6MTc1NzE2NjAyN30.9L7OWmE4VcqvQwTbexLDG-Qg0ug1ObMQQm-cg3sQzho

{
    "group":"Los pedros",
    "text":"I would love to join pedros"
}


###register an user
POST http://localhost:3000/register
Content-Type: application/json; charset=utf-8

{
    "username":"marcos",
    "user_password":"marcos1234",
    "country":"Spain",
    "city":"Vigo",
    "email":"marcos@email.com",
    "image":"http://localhost:3400/image.jpg",
    "name":"Marcos",
    "surname":"Sanchez"
    
}

###login an user
POST http://localhost:3000/login
Content-Type: application/json; charset=utf-8

{
    "username":"_davisanchez",
    "user_password":"davi1234"
}

###create group and set user logged is as admin
POST http://localhost:3000/create-group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicGVkcm8iLCJpYXQiOjE3NTcxNjIzNDYsImV4cCI6MTc1NzE2NTk0Nn0.-Qtz-RrV_u5pGcVtaIqeSahFEV_KzBuvS4TWRoE6PMg
Content-Type: application/json; charset=utf-8


{
    "name":"Los pedros"
}

###add to group by username
POST http://localhost:3000/add-to-group
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2FybGEiLCJpYXQiOjE3NTY5ODkxMjksImV4cCI6MTc1Njk5MjcyOX0.zRvKSh53RkopQ0FXmRAAK-nDOKZ_0MGvW4tyZ3sYZqE

{
    "name":"pablo",
    "group":"Las acacias"
}

### create header
POST http://localhost:3000/create-header
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiY2FybGEiLCJpYXQiOjE3NTY5ODkxMjksImV4cCI6MTc1Njk5MjcyOX0.zRvKSh53RkopQ0FXmRAAK-nDOKZ_0MGvW4tyZ3sYZqE
Content-Type: application/json; charset=utf-8

{
    "name":"Diario de carlas",
    "isPublic":false,
    "group":"Las carlas",
    "description":"Such a cool header"
}


###publish news
POST http://localhost:3000/publish-news
Content-Type: application/json; charset=utf-8

{
  "header": "Diario de juanes",
  "section": "Gente",
  "image": "http://example",
  "title": "El lenguaje secreto de las miradas en una relación amorosa",
  "subtitle": "Un estrevela cómo los gestos no verbales fortalecen la intimidad entre parejas",
  "content": "Las miradas, las sonrisas y los silencios compartidos forman parte de un lenguaje que muchas veces trasciende las palabras en una relación. Especialistas en comunicación no verbal explican que, cuando una pareja aprende a interpretar estos códigos íntimos, se crea un vínculo de confianza y complicidad difícil de romper. Aunque la vida cotidiana esté cargada de responsabilidades y estrés, detenerse a observar al otro y reconocer esos pequeños gestos de afecto puede marcar la diferencia en la calidad de la relación. El contacto visual, por ejemplo, genera una sensación de seguridad y validación que ayuda a consolidar la unión emocional. Asimismo, las expresiones de ternura espontáneas, como una sonrisa inesperada o un roce suave en la mano, son señales que transmiten cuidado y cercanía. En definitiva, el amor no solo se expresa con palabras: también se sostiene con un lenguaje silencioso que alimenta la confianza y fortalece el lazo afectivo día tras día.",
  "caption": "Una pareja compartiendo una mirada cómplice durante un paseo al aire libre.",
  "tags":[]
}

###like some news
POST http://localhost:3000/like-news
Content-Type: application/json; charset=utf-8

{
    "newsId":"206a3fc4-88d4-11f0-9572-0a0027000005"
}

###give a comment
POST http://localhost:3000/leave-comment
Content-Type: application/json; charset=utf-8

{
    "newsId":"206a3fc4-88d4-11f0-9572-0a0027000005",
    "comment":"also loved this post"
}




